backend:
  name: git-gateway
  branch: master

site_url: https://mrseaonline.com.ng
display_url: https://mrseaonline.com.ng

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "technology_posts"
    label: "Tech Posts"
    label_singular: "Post"
    folder: "content/posts"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}} [{{category}}]"
    create: true
    slug: "{{slug}}"
    filter: { field: "category", value: "Technology" }
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - {
          label: "Title of Post",
          name: "title",
          widget: "string",
          required: true,
          tagName: "h1",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "date",
          dateFormat: "YYYY/MM/DD",
          format: "YYYY/MM/DD",
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Technology", "Education"],
        }
      - {
          label: "Cover Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - label: "Author of Post"
        name: "author"
        widget: "relation"
        collection: "authors"
        displayFields: ["name", "email"]
        searchFields: ["name", "email"]
        valueField: "name"
      - { label: "Post Summary", name: "summary", widget: "text" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          hint: "Main content goes here.",
        }
      - { label: "SEO Description", name: "tags", widget: "text" }

  - name: "education_posts"
    label: "Edu Posts"
    label_singular: "Post"
    folder: "content/posts"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}} [{{category}}]"
    create: true
    slug: "{{slug}}"
    filter: { field: "category", value: "Education" }
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - {
          label: "Title of Post",
          name: "title",
          widget: "string",
          required: true,
          tagName: "h1",
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "date",
          dateFormat: "MM/DD/YYYY",
          format: "MM/DD/YYYY",
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Technology", "Education"],
        }
      - {
          label: "Cover Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - label: "Author of Post"
        name: "author"
        widget: "relation"
        collection: "authors"
        displayFields: ["name", "email"]
        searchFields: ["name", "email"]
        valueField: "name"
      - { label: "Post Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "SEO Description", name: "description", widget: "text" }

  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    folder: "authors"
    create: true
    summary: "{{name}}---{{email}}"
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Email Address", name: "email", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - {
          label: "Profession",
          name: "profession",
          widget: "string",
          required: false,
        }
      - {
          label: "About Me",
          name: "about-me",
          widget: "markdown",
          required: false,
        }

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    create: true
    summary: {{title}}
    folder: 'data/pages'
      - name: "portfolio"
        label: "Portfolio"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "string",
              default: "About me",
            }
          - { label: "About Me", name: "about-me", widget: "markdown" }
          - { label: "Skills", name: "skills", widget: "text" }
          - { label: "Hire Me", name: "hire-me", widget: "markdown" }
          - { label: "keywords", name: "keywords", widget: "text" }
          - { label: "Photo", name: "photo", widget: "image", required: false }
